#!/bin/sh
set -e

FILES=$(git diff --name-only --cached -- '*.py')

if [ -n "$FILES" ]; then
  uv run ruff format --check $FILES
  uv run ruff check $FILES
else
  uv run ruff format --check .
  uv run ruff check .
fi
