#!/bin/sh
set -e

FILES=$(git diff --name-only --cached -- '*.py')

if [ -z "$FILES" ]; then
  exit 0
fi

uv run ruff check --fix $FILES
uv run ruff format $FILES

git add $FILES

uv run ruff format --check $FILES
uv run ruff check $FILES
